
###
POST http://localhost:8080/app/add
Content-Type: application/json

{
  "url": "https://itunes.apple.com/cn/app/%E5%86%B0%E5%86%BB%E7%AC%A6%E6%96%87/id1458310065?mt=8"
}

###
POST http://47.99.200.185/app/add
Content-Type: application/json

{
  "url": [
    "https://itunes.apple.com/cn/app/bandizip-%E5%8E%8B%E7%BC%A9%E5%92%8C%E8%A7%A3%E5%8E%8B%E7%BC%A9/id1265704574?mt=12"
  ]
}

###
